# Generated by Django 3.1.2 on 2021-01-26 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0003_auto_20210119_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail_retrait',
            name='espece',
        ),
        migrations.RemoveField(
            model_name='detail_retrait',
            name='pepiniere',
        ),
        migrations.DeleteModel(
            name='Detail_Pepiniere',
        ),
        migrations.DeleteModel(
            name='Detail_Retrait',
        ),
        migrations.DeleteModel(
            name='Pepiniere',
        ),
    ]
