# Generated by Django 3.1.2 on 2021-03-01 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chocolotiers', '0001_initial'),
        ('parametres', '0004_auto_20210126_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chocolotiers.client', verbose_name='CLIENT'),
        ),
    ]
