# Generated by Django 3.1.7 on 2021-04-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0005_projet_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campagne',
            options={'ordering': ['-titre'], 'verbose_name': 'campagne', 'verbose_name_plural': 'CAMPAGNES'},
        ),
        migrations.RemoveField(
            model_name='campagne',
            name='accronyme',
        ),
        migrations.RemoveField(
            model_name='campagne',
            name='add_le',
        ),
        migrations.RemoveField(
            model_name='campagne',
            name='annee',
        ),
        migrations.RemoveField(
            model_name='campagne',
            name='debut',
        ),
        migrations.RemoveField(
            model_name='campagne',
            name='fin',
        ),
        migrations.RemoveField(
            model_name='campagne',
            name='update_le',
        ),
        migrations.AddField(
            model_name='campagne',
            name='annee_debut',
            field=models.IntegerField(choices=[(2019, 2019), (2020, 2020), (2021, 2021)], default=2021, verbose_name='Année début'),
        ),
        migrations.AddField(
            model_name='campagne',
            name='annee_fin',
            field=models.IntegerField(default=2022, verbose_name='Année fin'),
        ),
        migrations.AddField(
            model_name='campagne',
            name='mois_debut',
            field=models.CharField(choices=[('JAN', 'JANVIER'), ('FEV', 'FEVRIER'), ('MAR', 'MARS'), ('AVR', 'AVRIL'), ('MAI', 'MAI'), ('JUN', 'JUIN'), ('JUL', 'JUILLET'), ('AUG', 'AOUT'), ('SEP', 'SEPTEMBRE'), ('OCT', 'OCTOBRE'), ('NOV', 'NOVEMBRE'), ('DEC', 'DECEMBRE')], default='NOV', max_length=50),
        ),
        migrations.AddField(
            model_name='campagne',
            name='mois_fin',
            field=models.CharField(choices=[('JAN', 'JANVIER'), ('FEV', 'FEVRIER'), ('MAR', 'MARS'), ('AVR', 'AVRIL'), ('MAI', 'MAI'), ('JUN', 'JUIN'), ('JUL', 'JUILLET'), ('AUG', 'AOUT'), ('SEP', 'SEPTEMBRE'), ('OCT', 'OCTOBRE'), ('NOV', 'NOVEMBRE'), ('DEC', 'DECEMBRE')], default='SEP', max_length=50),
        ),
        migrations.AlterField(
            model_name='campagne',
            name='titre',
            field=models.CharField(blank=True, editable=False, max_length=500, null=True),
        ),
    ]
