# Generated by Django 3.1.2 on 2021-01-26 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0004_auto_20210126_1055'),
        ('cooperatives', '0011_auto_20210122_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pepiniere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=250, verbose_name='DELEGATION REGIONALE')),
                ('ville', models.CharField(max_length=250, verbose_name='VILLE')),
                ('site', models.CharField(max_length=250, verbose_name='SITE')),
                ('latitude', models.CharField(blank=True, max_length=10, null=True)),
                ('longitude', models.CharField(blank=True, max_length=10, null=True)),
                ('technicien', models.CharField(max_length=255, verbose_name='NOM ET PRENOMS TECHNICIEN')),
                ('contacts_technicien', models.CharField(blank=True, max_length=50, null=True, verbose_name='CONTACTS TECHNICIEN')),
                ('superviseur', models.CharField(max_length=255, verbose_name='NOM ET PRENOMS TECHNICIEN')),
                ('contacts_superviseur', models.CharField(blank=True, max_length=50, null=True, verbose_name='CONTACTS SUPERVISUER')),
                ('sachet_recus', models.PositiveIntegerField(default=0, verbose_name='QTE TOTAL SACHET RECU')),
                ('production_plant', models.PositiveIntegerField(default=0, verbose_name='PLANTS A PRODUIRE')),
                ('production_realise', models.PositiveIntegerField(default=0, verbose_name='REALISATION')),
                ('pourcentage_prod', models.PositiveIntegerField(default=0, verbose_name='POURCENTAGE DE PRODUCTION')),
                ('plant_mature', models.PositiveIntegerField(default=0, verbose_name='NBRE PLANT MATURE')),
                ('plant_retire', models.PositiveIntegerField(default=0, verbose_name='NBRE TOTAL PLANT RETIRE')),
                ('add_le', models.DateTimeField(auto_now_add=True)),
                ('update_le', models.DateTimeField(auto_now=True)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperatives.cooperative')),
            ],
            options={
                'verbose_name': 'pépinière',
                'verbose_name_plural': 'PEPINIERES',
            },
        ),
        migrations.AlterField(
            model_name='parcelle',
            name='superficie',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.CreateModel(
            name='Semence_Pepiniere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production', models.PositiveIntegerField(default=0, verbose_name='NB PLANTS A PRODUIRE')),
                ('qte_recu', models.PositiveIntegerField(default=0, verbose_name='QTE RECU')),
                ('date', models.DateField(verbose_name='DATE RECEPTION')),
                ('add_le', models.DateTimeField(auto_now_add=True)),
                ('update_le', models.DateTimeField(auto_now=True)),
                ('espece_recu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.espece')),
                ('pepiniere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperatives.pepiniere')),
            ],
            options={
                'verbose_name': 'détail semence reçu',
                'verbose_name_plural': 'DETAILS SEMENCES RECUS',
            },
        ),
        migrations.CreateModel(
            name='Retrait_plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_retire', models.PositiveIntegerField(default=0, verbose_name='NBRE TOTAL DE PLANTS RETIRES')),
                ('date', models.DateField(verbose_name='DATE RETRAIT')),
                ('add_le', models.DateTimeField(auto_now_add=True)),
                ('update_le', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperatives.cooperative')),
                ('pepiniere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperatives.pepiniere')),
            ],
            options={
                'verbose_name': 'retrait plant',
                'verbose_name_plural': 'RETRAITS PLANTS',
            },
        ),
        migrations.CreateModel(
            name='Detail_Retrait_plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_retire', models.PositiveIntegerField(default=0, verbose_name='NBRE PLANT RETIRE')),
                ('date', models.DateField(verbose_name='DATE RETRAIT')),
                ('add_le', models.DateTimeField(auto_now_add=True)),
                ('update_le', models.DateTimeField(auto_now=True)),
                ('espece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.espece')),
                ('retait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperatives.retrait_plant')),
            ],
            options={
                'verbose_name': 'detail retrait plant',
                'verbose_name_plural': 'DETAILS RETRAITS PLANTS',
                'ordering': ['espece'],
            },
        ),
    ]
