# Generated by Django 3.1.2 on 2021-01-28 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0004_auto_20210126_1055'),
        ('cooperatives', '0014_auto_20210126_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planting',
            name='projet',
        ),
        migrations.AddField(
            model_name='details_planting',
            name='projet',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='parametres.projet'),
        ),
        migrations.AlterField(
            model_name='planting',
            name='nb_plant',
            field=models.PositiveIntegerField(default=0, verbose_name='NOMBRE TOTAL DE PLANTS RECUS'),
        ),
    ]
