# Generated by Django 3.1.2 on 2021-01-29 11:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0015_auto_20210128_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details_planting',
            name='observation',
        ),
        migrations.AddField(
            model_name='details_planting',
            name='add_le',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='details_planting',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='details_planting',
            name='update_le',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='planting',
            name='add_le',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planting',
            name='observation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planting',
            name='update_le',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
