# Generated by Django 3.1.2 on 2021-02-02 09:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0016_auto_20210129_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='retrait_plant',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='DATE RETRAIT'),
            preserve_default=False,
        ),
    ]
