# Generated by Django 3.1.2 on 2021-02-02 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0017_retrait_plant_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retrait_plant',
            name='cooperative',
        ),
    ]
