# Generated by Django 3.1.2 on 2021-02-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0018_remove_retrait_plant_cooperative'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail_formation',
            name='observation',
        ),
        migrations.AddField(
            model_name='formation',
            name='observation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
