# Generated by Django 3.1.2 on 2021-02-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0019_auto_20210209_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='retrait_plant',
            name='client',
            field=models.CharField(blank=True, max_length=255, verbose_name='CLIENT'),
        ),
    ]
