# Generated by Django 3.1.2 on 2021-03-01 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0020_retrait_plant_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parcelle',
            options={'verbose_name': 'parcelle', 'verbose_name_plural': 'PARCELLES'},
        ),
    ]
