# Generated by Django 3.1.2 on 2021-03-01 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0005_projet_client'),
        ('cooperatives', '0021_auto_20210301_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='projet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parametres.projet'),
        ),
        migrations.AddField(
            model_name='pepiniere',
            name='projet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parametres.projet'),
        ),
    ]
