# Generated by Django 3.1.2 on 2021-03-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0022_auto_20210301_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='producteur',
            name='prod_coop',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='producteur',
            name='prod_section',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
