# Generated by Django 3.1.2 on 2021-03-04 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0023_auto_20210304_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producteur',
            name='prod_coop',
        ),
        migrations.RemoveField(
            model_name='producteur',
            name='prod_section',
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_section', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('prod_coop', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperatives.cooperative')),
            ],
        ),
    ]
