# Generated by Django 3.1.7 on 2021-03-30 16:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0024_auto_20210304_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='producteur',
            name='add_le',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producteur',
            name='update_le',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
