# Generated by Django 3.1.7 on 2021-04-08 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0027_auto_20210407_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcelle',
            name='producteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelles', to='cooperatives.producteur'),
        ),
    ]
