# Generated by Django 3.2 on 2021-04-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0028_auto_20210408_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperative',
            name='siege',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SIEGE/LOCALITE'),
        ),
    ]
