# Generated by Django 3.1.7 on 2021-04-29 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0006_auto_20210407_0952'),
        ('cooperatives', '0029_cooperative_siege'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailsReception',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_plant_recu', models.PositiveIntegerField(default=0, verbose_name='NOMBRE PLANT RECUS')),
                ('add_le', models.DateTimeField(auto_now_add=True)),
                ('update_le', models.DateTimeField(auto_now=True)),
                ('espece', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parametres.espece')),
            ],
        ),
        migrations.CreateModel(
            name='Monitoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mort', models.PositiveIntegerField(default=0, verbose_name='NBRE PLANTS MORTS')),
                ('remplace', models.PositiveIntegerField(default=0, verbose_name='NBRE PLANTS REMPLACES')),
                ('mature', models.PositiveIntegerField(default=0, verbose_name='NBRE PLANTS MATURE')),
                ('observation', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('add_le', models.DateTimeField(auto_now_add=True)),
                ('update_le', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'monitoring',
                'verbose_name_plural': 'MONITORINGS',
            },
        ),
        migrations.CreateModel(
            name='Reception',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_plant_recus', models.PositiveIntegerField(default=0, verbose_name='NOMBRE TOTAL DE PLANTS RECUS')),
                ('date', models.DateField(verbose_name='Date Reception')),
                ('add_le', models.DateTimeField(auto_now_add=True)),
                ('update_le', models.DateTimeField(auto_now=True)),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperatives.parcelle')),
            ],
        ),
        migrations.RemoveField(
            model_name='planting',
            name='nb_plant',
        ),
        migrations.RemoveField(
            model_name='planting',
            name='observation',
        ),
        migrations.AddField(
            model_name='planting',
            name='espece',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parametres.espece'),
        ),
        migrations.AddField(
            model_name='planting',
            name='nb_plant_exitant',
            field=models.PositiveIntegerField(default=0, verbose_name='NBRE PLANTS EXISTANTS'),
        ),
        migrations.AddField(
            model_name='planting',
            name='nb_plante',
            field=models.PositiveIntegerField(default=0, verbose_name='NBRE PLANTS PLANTE/ESPECE'),
        ),
        migrations.AddField(
            model_name='planting',
            name='projet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parametres.projet'),
        ),
        migrations.DeleteModel(
            name='Details_planting',
        ),
        migrations.AddField(
            model_name='monitoring',
            name='planting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperatives.planting'),
        ),
        migrations.AddField(
            model_name='detailsreception',
            name='reception',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperatives.reception'),
        ),
    ]
