# Generated by Django 3.1.7 on 2021-04-29 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0030_auto_20210429_1058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detailsreception',
            options={'verbose_name': 'detail reception', 'verbose_name_plural': 'DETAILS RECEPTIONS'},
        ),
        migrations.AlterModelOptions(
            name='reception',
            options={'verbose_name': 'reception', 'verbose_name_plural': 'RECEPTIONS'},
        ),
    ]
