# Generated by Django 3.1.7 on 2021-04-29 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0006_auto_20210407_0952'),
        ('cooperatives', '0031_auto_20210429_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planting',
            name='espece',
        ),
        migrations.RemoveField(
            model_name='planting',
            name='nb_plante',
        ),
        migrations.AddField(
            model_name='planting',
            name='plant_recu',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.CreateModel(
            name='DetailPlanting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_plante', models.PositiveIntegerField(default=0, verbose_name='NBRE PLANTS PLANTE/ESPECE')),
                ('add_le', models.DateTimeField(auto_now_add=True)),
                ('update_le', models.DateTimeField(auto_now=True)),
                ('espece', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parametres.espece')),
                ('planting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperatives.planting')),
            ],
            options={
                'verbose_name': 'details planting',
                'verbose_name_plural': 'DETAILS PLANTINGS',
            },
        ),
    ]
