# Generated by Django 3.1.7 on 2021-04-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0033_auto_20210429_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='planting',
            name='plant_recus',
            field=models.PositiveIntegerField(default=0, verbose_name='NOMBRE DE PLANTS RECUS'),
        ),
        migrations.AddField(
            model_name='planting',
            name='plant_total',
            field=models.PositiveIntegerField(default=0, verbose_name='NOMBRE TOTAL DE PLANTS'),
        ),
    ]
