# Generated by Django 3.1.7 on 2021-04-30 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0034_auto_20210429_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planting',
            name='plant_recu',
        ),
    ]
