# Generated by Django 3.1.7 on 2021-05-14 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0035_remove_planting_plant_recu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailsreception',
            name='reception',
        ),
        migrations.DeleteModel(
            name='Reception',
        ),
    ]
