# Generated by Django 3.1.7 on 2021-05-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0036_auto_20210514_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='producteur',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
