# Generated by Django 3.1.7 on 2021-05-21 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0006_auto_20210407_0952'),
        ('cooperatives', '0037_producteur_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monitoring',
            options={'verbose_name': 'details planting', 'verbose_name_plural': 'DETAILS PLANTINGS'},
        ),
        migrations.RenameField(
            model_name='monitoring',
            old_name='remplace',
            new_name='nb_plante',
        ),
        migrations.RemoveField(
            model_name='monitoring',
            name='date',
        ),
        migrations.RemoveField(
            model_name='monitoring',
            name='mature',
        ),
        migrations.RemoveField(
            model_name='monitoring',
            name='mort',
        ),
        migrations.AddField(
            model_name='monitoring',
            name='espece',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parametres.espece'),
        ),
    ]
