# Generated by Django 3.1.7 on 2021-05-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0038_auto_20210521_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoring',
            name='mature',
            field=models.PositiveIntegerField(default=0, verbose_name='NBRE PLANTS VIVANTS'),
        ),
        migrations.AddField(
            model_name='monitoring',
            name='mort',
            field=models.PositiveIntegerField(default=0, verbose_name='NBRE PLANTS MORTS'),
        ),
        migrations.AddField(
            model_name='monitoring',
            name='remplace',
            field=models.PositiveIntegerField(default=0, verbose_name='NBRE PLANTS REMPLACES'),
        ),
    ]
