# Generated by Django 3.1.7 on 2021-05-21 09:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0039_auto_20210521_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoring',
            name='nb_plante',
        ),
        migrations.AddField(
            model_name='monitoring',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
