# Generated by Django 3.1.7 on 2021-05-25 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0040_auto_20210521_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planting',
            name='details',
        ),
    ]
