# Generated by Django 3.1.7 on 2021-05-31 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0041_remove_planting_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcelle',
            name='add_le',
        ),
        migrations.RemoveField(
            model_name='parcelle',
            name='update_le',
        ),
        migrations.RemoveField(
            model_name='producteur',
            name='add_le',
        ),
        migrations.RemoveField(
            model_name='producteur',
            name='update_le',
        ),
    ]
