# Generated by Django 3.1.7 on 2021-05-31 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0042_auto_20210531_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planting',
            name='campagne',
            field=models.CharField(blank=True, default='2020-2021', max_length=10, null=True),
        ),
    ]
