# Generated by Django 3.1.7 on 2021-05-25 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import planting_communautaire.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parametres', '0006_auto_20210407_0952'),
        ('chocolotiers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siege', models.CharField(blank=True, max_length=255, null=True, verbose_name='SIEGE/LOCALITE')),
                ('sigle', models.CharField(max_length=500, verbose_name='SIGNE COMMUNAUTE')),
                ('libelle', models.CharField(max_length=255, verbose_name='NOM COMMUNAUTE')),
                ('localisation', models.CharField(max_length=255, verbose_name='LOCALISATION')),
                ('responsable', models.CharField(max_length=255, verbose_name='NOM ET PRENOMS RESPONSABLE')),
                ('contacts', models.CharField(blank=True, max_length=50, null=True)),
                ('culture_associee', models.CharField(choices=[('banane', 'BANANE'), ('mais', 'MAIS'), ('coton', 'COTON'), ('coton', 'COTON')], max_length=50, verbose_name='CULTURE ASSOCIEE')),
                ('logo', models.ImageField(blank=True, upload_to=planting_communautaire.models.upload_logo_site, verbose_name='Logo')),
                ('add_le', models.DateTimeField(auto_now_add=True)),
                ('update_le', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chocolotiers.client')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.region')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Communaute',
                'verbose_name_plural': 'COMMUNAUTE',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=150, null=True, verbose_name='CODE PARCELLE')),
                ('latitude', models.CharField(max_length=10)),
                ('longitude', models.CharField(max_length=10)),
                ('superficie', models.DecimalField(blank=True, decimal_places=12, max_digits=15, null=True)),
                ('culture', models.CharField(choices=[('anacarde', 'ANACARDE'), ('cacao', 'CACAO'), ('cafe', 'CAFE'), ('coton', 'COTON'), ('hevea', 'HEVEA'), ('palmier', 'PALMIER A HUILE'), ('SOJA', 'SOJA'), ('autre', 'AUTRES')], max_length=50, verbose_name='CULTURE')),
                ('culture_associee', models.CharField(choices=[('banane', 'BANANE'), ('mais', 'MAIS'), ('coton', 'COTON'), ('coton', 'COTON')], max_length=50, verbose_name='CULTURE ASSOCIEE')),
                ('add_le', models.DateTimeField(auto_now_add=True)),
                ('update_le', models.DateTimeField(auto_now=True)),
                ('communaute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planting_communautaire.organisation')),
            ],
            options={
                'verbose_name': 'parcelle',
                'verbose_name_plural': 'PARCELLES',
            },
        ),
        migrations.CreateModel(
            name='Planting_Com',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_plant_exitant', models.PositiveIntegerField(default=0, verbose_name='NBRE PLANTS EXISTANTS')),
                ('nb_plant', models.PositiveIntegerField(default=0)),
                ('plant_total', models.PositiveIntegerField(default=0, verbose_name='NOMBRE TOTAL DE PLANTS')),
                ('date', models.DateField()),
                ('add_le', models.DateTimeField(auto_now_add=True)),
                ('update_le', models.DateTimeField(auto_now=True)),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.campagne')),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planting_communautaire.parcelle')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.projet')),
            ],
            options={
                'verbose_name': 'planting communautaire',
                'verbose_name_plural': 'PLANTINGS COMMUNAUTAIRES',
            },
        ),
        migrations.CreateModel(
            name='Monitoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mort', models.PositiveIntegerField(default=0, verbose_name='NBRE PLANTS MORTS')),
                ('remplace', models.PositiveIntegerField(default=0, verbose_name='NBRE PLANTS REMPLACES')),
                ('mature', models.PositiveIntegerField(default=0, verbose_name='NBRE PLANTS VIVANTS')),
                ('observation', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('add_le', models.DateTimeField(auto_now_add=True)),
                ('update_le', models.DateTimeField(auto_now=True)),
                ('espece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='espece_monitoring', to='parametres.espece')),
                ('planting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planting_communautaire.planting_com')),
            ],
            options={
                'verbose_name': 'details planting',
                'verbose_name_plural': 'DETAILS PLANTINGS',
            },
        ),
        migrations.CreateModel(
            name='DetailPlanting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_plante', models.PositiveIntegerField(default=0, verbose_name='NBRE PLANTS PLANTE/ESPECE')),
                ('add_le', models.DateTimeField(auto_now_add=True)),
                ('update_le', models.DateTimeField(auto_now=True)),
                ('espece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='espece_planting', to='parametres.espece')),
                ('planting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planting_communautaire.planting_com')),
            ],
            options={
                'verbose_name': 'detail planting',
                'verbose_name_plural': 'DETAILS PLANTINGS',
            },
        ),
    ]
