# Generated by Django 3.1.7 on 2021-05-25 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planting_communautaire', '0002_remove_organisation_localisation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monitoring',
            options={'verbose_name': 'details planting', 'verbose_name_plural': 'MONITORINGS PLANTINGS'},
        ),
        migrations.AlterModelOptions(
            name='parcelle',
            options={'verbose_name': 'parcelle communautaire', 'verbose_name_plural': 'PARCELLES COMMUNAUTAIRES'},
        ),
    ]
