# Generated by Django 3.1.7 on 2021-05-25 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planting_communautaire', '0003_auto_20210525_1404'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organisation',
            options={'ordering': ['libelle'], 'verbose_name': 'Communaute', 'verbose_name_plural': 'COMMUNAUTES'},
        ),
    ]
