# Generated by Django 3.1.7 on 2021-05-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0006_auto_20210407_0952'),
        ('planting_communautaire', '0004_auto_20210525_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='projet_com',
            field=models.ManyToManyField(default=1, related_name='projet_commaunautaire', to='parametres.Projet'),
        ),
    ]
