# Generated by Django 3.1.7 on 2021-05-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0006_auto_20210407_0952'),
        ('planting_communautaire', '0005_organisation_projet_com'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='projet_com',
            field=models.ManyToManyField(related_name='projet_commaunautaire', to='parametres.Projet'),
        ),
    ]
