# Generated by Django 3.1.7 on 2021-05-26 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planting_communautaire', '0006_auto_20210526_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='culture_associee',
        ),
    ]
