# Generated by Django 3.1.7 on 2021-05-26 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0006_auto_20210407_0952'),
        ('planting_communautaire', '0007_remove_organisation_culture_associee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='sigle',
            field=models.CharField(max_length=500, verbose_name='SIGLE COMMUNAUTE'),
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formateur', models.CharField(max_length=255, verbose_name='FORMATEUR')),
                ('libelle', models.CharField(max_length=500, verbose_name='INTITULE DE LA FORMATION')),
                ('debut', models.DateField(verbose_name='DATE DEBUT')),
                ('fin', models.DateField(verbose_name='DATE FIN')),
                ('observation', models.TextField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('add_le', models.DateTimeField(auto_now_add=True)),
                ('update_le', models.DateTimeField(auto_now=True)),
                ('campagne_formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campagne_formation', to='parametres.campagne')),
                ('communaute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planting_communautaire.organisation')),
                ('projet_formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projet_formation', to='parametres.projet')),
            ],
            options={
                'verbose_name': 'formation',
                'verbose_name_plural': 'FORMATIONS',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Detail_Formation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prenoms', models.CharField(max_length=500)),
                ('contacts', models.CharField(blank=True, max_length=50, null=True)),
                ('localite', models.CharField(blank=True, max_length=50, null=True)),
                ('add_le', models.DateTimeField(auto_now_add=True)),
                ('update_le', models.DateTimeField(auto_now=True)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planting_communautaire.formation')),
            ],
            options={
                'verbose_name': 'details formation',
                'verbose_name_plural': 'DETAILS FORMATIONS',
            },
        ),
    ]
