# Generated by Django 3.1.7 on 2021-05-26 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planting_communautaire', '0008_auto_20210526_1404'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formation',
            options={'ordering': ['libelle'], 'verbose_name': 'formation & sensibilisation', 'verbose_name_plural': 'FORMATIONS & SENSIBILISATIONS'},
        ),
        migrations.RenameField(
            model_name='parcelle',
            old_name='culture_associee',
            new_name='associee',
        ),
    ]
