# Generated by Django 3.1.7 on 2021-05-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planting_communautaire', '0009_auto_20210526_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcelle',
            name='superficie',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
    ]
